# Generated by Django 6.0.4 on 2026-04-27 10:57

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('seo_title_custom', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO description')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Текст страницы')),
            ],
            options={
                'verbose_name': 'Юридическая страница',
                'verbose_name_plural': 'Юридические страницы',
            },
            bases=('wagtailcore.page',),
        ),
    ]
