# Generated by Django 6.0.4 on 2026-04-21 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('seo_title_custom', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO description')),
                ('hero_badge', models.CharField(blank=True, max_length=255, verbose_name='Бейдж в hero')),
                ('hero_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок hero')),
                ('hero_description', models.TextField(blank=True, verbose_name='Описание hero')),
                ('intro_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок блока описания')),
                ('intro_text', models.TextField(blank=True, verbose_name='Текст описания')),
                ('feature_1_title', models.CharField(blank=True, max_length=255, verbose_name='Преимущество 1 — заголовок')),
                ('feature_1_text', models.TextField(blank=True, verbose_name='Преимущество 1 — текст')),
                ('feature_2_title', models.CharField(blank=True, max_length=255, verbose_name='Преимущество 2 — заголовок')),
                ('feature_2_text', models.TextField(blank=True, verbose_name='Преимущество 2 — текст')),
                ('feature_3_title', models.CharField(blank=True, max_length=255, verbose_name='Преимущество 3 — заголовок')),
                ('feature_3_text', models.TextField(blank=True, verbose_name='Преимущество 3 — текст')),
                ('step_1_title', models.CharField(blank=True, max_length=255, verbose_name='Этап 1 — заголовок')),
                ('step_1_text', models.TextField(blank=True, verbose_name='Этап 1 — текст')),
                ('step_2_title', models.CharField(blank=True, max_length=255, verbose_name='Этап 2 — заголовок')),
                ('step_2_text', models.TextField(blank=True, verbose_name='Этап 2 — текст')),
                ('step_3_title', models.CharField(blank=True, max_length=255, verbose_name='Этап 3 — заголовок')),
                ('step_3_text', models.TextField(blank=True, verbose_name='Этап 3 — текст')),
                ('cta_title', models.CharField(blank=True, max_length=255, verbose_name='CTA заголовок')),
                ('cta_text', models.TextField(blank=True, verbose_name='CTA текст')),
                ('cta_button_text', models.CharField(blank=True, max_length=255, verbose_name='Текст кнопки CTA')),
                ('cta_button_link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка кнопки CTA')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение hero')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
