# Generated by Django 6.0.4 on 2026-04-27 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicepage',
            options={'verbose_name': 'Страница услуги'},
        ),
    ]
