# Generated by Django 6.0.4 on 2026-04-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_title_custom',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO title'),
        ),
    ]
