# Generated by Django 6.0.4 on 2026-04-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_seo_description_homepage_seo_title_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_text',
            field=models.TextField(blank=True, default='Для B2B-клиента важен не только сам вывоз отходов, но и управляемый процесс: соблюдение графика, наличие транспорта, понятная коммуникация и документы.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(blank=True, default='Не просто вывозим, а выстраиваем сервис', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='company_address',
            field=models.CharField(blank=True, default='Краснодарский край, станица Нижнебаканская', max_length=255, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='company_city',
            field=models.CharField(blank=True, default='Новороссийск', max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='company_email',
            field=models.EmailField(blank=True, default='info@example.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='company_name',
            field=models.CharField(blank=True, default='ООО «Баканка»', max_length=255, verbose_name='Название компании для schema.org'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='company_phone',
            field=models.CharField(blank=True, default='+7 (999) 999-99-99', max_length=100, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_1_text',
            field=models.CharField(blank=True, default='Оперативный вывоз по Новороссийску и близлежащим территориям', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_1_title',
            field=models.CharField(blank=True, default='Собственный транспорт', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_2_text',
            field=models.CharField(blank=True, default='Документальное сопровождение и понятные условия для B2B', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_2_title',
            field=models.CharField(blank=True, default='Работа по договору', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_3_text',
            field=models.CharField(blank=True, default='Подбираем решение под тип отходов, объем и специфику объекта', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_3_title',
            field=models.CharField(blank=True, default='Системный подход', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_badge',
            field=models.CharField(blank=True, default='B2B · Новороссийск · Нижнебаканская', max_length=255, verbose_name='Hero badge'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_description',
            field=models.TextField(blank=True, verbose_name='Hero description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_button_link',
            field=models.CharField(blank=True, default='#request', max_length=255, verbose_name='Ссылка основной кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_button_text',
            field=models.CharField(blank=True, default='Получить расчет', max_length=100, verbose_name='Текст основной кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_button_link',
            field=models.CharField(blank=True, default='#services', max_length=255, verbose_name='Ссылка второй кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_button_text',
            field=models.CharField(blank=True, default='Наши услуги', max_length=100, verbose_name='Текст второй кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Вывоз и утилизация отходов для бизнеса', max_length=255, verbose_name='Hero title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='panel_item_1',
            field=models.CharField(blank=True, default='Строительные отходы', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='panel_item_2',
            field=models.CharField(blank=True, default='Производственные отходы', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='panel_item_3',
            field=models.CharField(blank=True, default='Контейнерный вывоз', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='panel_item_4',
            field=models.CharField(blank=True, default='Сопровождение заявок и документов', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='panel_label',
            field=models.CharField(blank=True, default='Экологические решения', max_length=255, verbose_name='Подпись на правой панели'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='panel_title',
            field=models.CharField(blank=True, default='Надежный подрядчик для бизнеса', max_length=255, verbose_name='Заголовок правой панели'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='request_text',
            field=models.TextField(blank=True, default='Подготовим предложение под тип отходов, объем работ, адрес объекта и формат взаимодействия.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='request_title',
            field=models.CharField(blank=True, default='Оставьте запрос на расчет', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_1_text',
            field=models.TextField(blank=True, default='Вывоз отходов после строительства, ремонта, демонтажа и расчистки территории.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_1_title',
            field=models.CharField(blank=True, default='Вывоз строительных отходов', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_2_text',
            field=models.TextField(blank=True, default='Решения для производств, цехов, складов и промышленных площадок.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_2_title',
            field=models.CharField(blank=True, default='Вывоз производственных отходов', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_3_text',
            field=models.TextField(blank=True, default='Подбор техники, графика вывоза и схемы обслуживания объекта.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_3_title',
            field=models.CharField(blank=True, default='Контейнеры и логистика', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_4_text',
            field=models.TextField(blank=True, default='Договоры, заявки, акты и понятный процесс взаимодействия с клиентом.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_4_title',
            field=models.CharField(blank=True, default='Документальное сопровождение', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_section_text',
            field=models.TextField(blank=True, default='Работаем со стройками, предприятиями, подрядными организациями, складскими и коммерческими объектами.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_section_title',
            field=models.CharField(blank=True, default='Основные направления работы', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat_1_text',
            field=models.CharField(blank=True, default='работаем с юридическими лицами', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat_1_title',
            field=models.CharField(blank=True, default='B2B', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat_2_text',
            field=models.CharField(blank=True, default='и станица Нижнебаканская', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat_2_title',
            field=models.CharField(blank=True, default='Новороссийск', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat_3_text',
            field=models.CharField(blank=True, default='от заявки до сопровождения', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat_3_title',
            field=models.CharField(blank=True, default='Полный цикл', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='seo_title_custom',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO Title'),
        ),
    ]
