# Generated by Django 6.0.4 on 2026-04-09 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_about_text_homepage_about_title_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Главная страница'},
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='company_city',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='company_phone',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_text',
            field=models.TextField(blank=True, default='Для B2B-клиента важен не только сам вывоз отходов, но и управляемый процесс: соблюдение графика, наличие транспорта, понятная коммуникация и документы.', verbose_name='Текст блока о компании'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(blank=True, default='Не просто вывозим, а выстраиваем сервис', max_length=255, verbose_name='Заголовок блока о компании'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='feature_1_text',
            field=models.CharField(blank=True, default='Оперативный вывоз по Новороссийску и близлежащим территориям', max_length=255, verbose_name='Преимущество 1 — текст'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='feature_1_title',
            field=models.CharField(blank=True, default='Собственный транспорт', max_length=255, verbose_name='Преимущество 1 — заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='feature_2_text',
            field=models.CharField(blank=True, default='Документальное сопровождение и понятные условия для B2B', max_length=255, verbose_name='Преимущество 2 — текст'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='feature_2_title',
            field=models.CharField(blank=True, default='Работа по договору', max_length=255, verbose_name='Преимущество 2 — заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='feature_3_text',
            field=models.CharField(blank=True, default='Подбираем решение под тип отходов, объем и специфику объекта', max_length=255, verbose_name='Преимущество 3 — текст'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='feature_3_title',
            field=models.CharField(blank=True, default='Системный подход', max_length=255, verbose_name='Преимущество 3 — заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='panel_item_1',
            field=models.CharField(blank=True, default='Строительные отходы', max_length=255, verbose_name='Пункт панели 1'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='panel_item_2',
            field=models.CharField(blank=True, default='Производственные отходы', max_length=255, verbose_name='Пункт панели 2'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='panel_item_3',
            field=models.CharField(blank=True, default='Контейнерный вывоз', max_length=255, verbose_name='Пункт панели 3'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='panel_item_4',
            field=models.CharField(blank=True, default='Сопровождение заявок и документов', max_length=255, verbose_name='Пункт панели 4'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='request_text',
            field=models.TextField(blank=True, default='Подготовим предложение под тип отходов, объем работ, адрес объекта и формат взаимодействия.', verbose_name='Текст блока заявки'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='request_title',
            field=models.CharField(blank=True, default='Оставьте запрос на расчет', max_length=255, verbose_name='Заголовок блока заявки'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Краткое описание страницы для поисковых систем.', verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='seo_title_custom',
            field=models.CharField(blank=True, help_text='Если заполнено, будет использоваться вместо стандартного title страницы.', max_length=255, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='service_1_text',
            field=models.TextField(blank=True, default='Вывоз отходов после строительства, ремонта, демонтажа и расчистки территории.', verbose_name='Услуга 1 — текст'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='service_1_title',
            field=models.CharField(blank=True, default='Вывоз строительных отходов', max_length=255, verbose_name='Услуга 1 — заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='service_2_text',
            field=models.TextField(blank=True, default='Решения для производств, цехов, складов и промышленных площадок.', verbose_name='Услуга 2 — текст'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='service_2_title',
            field=models.CharField(blank=True, default='Вывоз производственных отходов', max_length=255, verbose_name='Услуга 2 — заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='service_3_text',
            field=models.TextField(blank=True, default='Подбор техники, графика вывоза и схемы обслуживания объекта.', verbose_name='Услуга 3 — текст'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='service_3_title',
            field=models.CharField(blank=True, default='Контейнеры и логистика', max_length=255, verbose_name='Услуга 3 — заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='service_4_text',
            field=models.TextField(blank=True, default='Договоры, заявки, акты и понятный процесс взаимодействия с клиентом.', verbose_name='Услуга 4 — текст'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='service_4_title',
            field=models.CharField(blank=True, default='Документальное сопровождение', max_length=255, verbose_name='Услуга 4 — заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='services_section_text',
            field=models.TextField(blank=True, default='Работаем со стройками, предприятиями, подрядными организациями, складскими и коммерческими объектами.', verbose_name='Описание блока услуг'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='services_section_title',
            field=models.CharField(blank=True, default='Основные направления работы', max_length=255, verbose_name='Заголовок блока услуг'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='stat_1_text',
            field=models.CharField(blank=True, default='работаем с юридическими лицами', max_length=255, verbose_name='Статистика 1 — текст'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='stat_1_title',
            field=models.CharField(blank=True, default='B2B', max_length=255, verbose_name='Статистика 1 — заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='stat_2_text',
            field=models.CharField(blank=True, default='и станица Нижнебаканская', max_length=255, verbose_name='Статистика 2 — текст'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='stat_2_title',
            field=models.CharField(blank=True, default='Новороссийск', max_length=255, verbose_name='Статистика 2 — заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='stat_3_text',
            field=models.CharField(blank=True, default='от заявки до сопровождения', max_length=255, verbose_name='Статистика 3 — текст'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='stat_3_title',
            field=models.CharField(blank=True, default='Полный цикл', max_length=255, verbose_name='Статистика 3 — заголовок'),
        ),
        migrations.CreateModel(
            name='SiteContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='ООО «Баканка»', max_length=255, verbose_name='Название компании')),
                ('phone', models.CharField(blank=True, default='+7 (999) 999-99-99', max_length=100, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='info@example.com', max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, default='Краснодарский край, станица Нижнебаканская', max_length=255, verbose_name='Адрес')),
                ('city', models.CharField(blank=True, default='Новороссийск', max_length=100, verbose_name='Город')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Контакты сайта',
            },
        ),
    ]
