# Generated by Django 6.0.4 on 2026-04-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='is_processed',
        ),
        migrations.AddField(
            model_name='lead',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес'),
        ),
        migrations.AddField(
            model_name='lead',
            name='page_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='URL страницы'),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Обработана'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='lead',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User-Agent'),
        ),
    ]
