# Generated by Django 6.0.4 on 2026-04-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_lead_is_processed_lead_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='SEO description'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='seo_title_custom',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO title'),
        ),
    ]
