# Generated by Django 6.0.4 on 2026-04-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_homepage_seo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия'),
        ),
        migrations.AddField(
            model_name='lead',
            name='consent_personal_data',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку ПДн'),
        ),
        migrations.AddField(
            model_name='lead',
            name='consent_policy_version',
            field=models.CharField(blank=True, default='policy_2026_04_27', max_length=100, verbose_name='Версия политики'),
        ),
    ]
